platform: x64
configuration: Release
version: 1.0.{build}
skip_non_tags: true
skip_branch_with_pr: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build:
  publish_nuget: true
  parallel: true
  project: ModernDev.InTouch.sln

before_build:
  - nuget restore
  
after_build:
  - nuget pack ModernDev.InTouch.nuspec -version %APPVEYOR_BUILD_VERSION%
  - appveyor PushArtifact ModernDev.InTouch.%APPVEYOR_BUILD_VERSION%.nupkg

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true
  
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/fccbbe8e33b7c9ea1f62
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
  
deploy:
- provider: NuGet
  api_key:
    secure: VgpA4NJgZjB689R1BP3A4bbtQzjprU8U/Cgre7NS5IDWxry5Z9WxhFUqz8lWsRnw
  artifact: /.*\.nupkg/
